spring:
    datasource:
        driverClassName: "org.h2.Driver"
        url: "jdbc:h2:mem:test"
        username: "sa"
        password: ""
    jpa:
        databasePlatform: "org.hibernate.dialect.H2Dialect"
        showSql: true
    h2:
        console:
            enabled: true
